export enum GalleryActionTypes {
  SET_GALLERIES = "SET_GALLERIES",
  SET_LIKE_FETCHING = "SET_LIKE_FETCHING",
  SET_DISLIKE_FETCHING = "SET_DISLIKE_FETCHING",
  SET_GALLERY_FETCHING = "SET_GALLERY_FETCHING",
  SET_LIKED = "SET_LIKED",
  SET_UNLIKED = "SET_UNLIKED",
  SET_DISLIKED = "SET_DISLIKED",
  SET_UNDISLIKED = "SET_UNDISLIKED",
  HYDRATE = "__NEXT_REDUX_WRAPPER_HYDRATE__",
}
