export enum GalleryActionTypes {
  SET_GALLERIES = "SET_GALLERIES",
  SET_LIKE_FETCHING = "SET_LIKE_FETCHING",
  SET_DISLIKE_FETCHING = "SET_DISLIKE_FETCHING",
  SET_GALLERY_FETCHING = "SET_GALLERY_FETCHING",
}
