export enum UserActionTypes {
  FETCH_APP = "FETCH_APP",
  FETCH_APP_SUCCESS = "FETCH_APP_SUCCESS",
  FETCH_APP_ERROR = "FETCH_APP_ERROR",
  SET_MODAL_MESSAGE = "SET_MODAL_MESSAGE",
  SET_IS_AUTH = "SET_IS_AUTH",
  SET_AUTH_USER = "SET_AUTH_USER",
  SET_LIKED_POSTS = "SET_LIKED_POSTS",
}
